apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
  labels:
    app: file
spec:
  replicas: {{ .Values.file.replicas }}
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
      - name: file
        imagePullPolicy: Always
        image: quay.io/fdavalo/app-test-storage:v1 
        command: ["sh", "-c", "cd src; python3 server.py"]
        env:
        - name: FS
          value: /var/lib/data
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/lib/data
          name: data     
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: file-data
