kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: app-test-storage
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'app-test-storage:v1'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8'
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/app-test-storage.git'
      ref: main
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
